[2024-10-06T20:12:56.800+0000] {processor.py:186} INFO - Started process (PID=1230) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:12:56.800+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:12:56.803+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:12:56.802+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:12:56.826+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:12:56.820+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:12:56.831+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:12:56.856+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.061 seconds
[2024-10-06T20:13:27.079+0000] {processor.py:186} INFO - Started process (PID=1246) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:13:27.080+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:13:27.083+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:13:27.083+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:13:27.098+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:13:27.093+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:13:27.103+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:13:27.120+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.045 seconds
[2024-10-06T20:13:57.334+0000] {processor.py:186} INFO - Started process (PID=1262) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:13:57.335+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:13:57.337+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:13:57.336+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:13:57.351+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:13:57.345+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:13:57.355+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:13:57.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.041 seconds
[2024-10-06T20:14:27.599+0000] {processor.py:186} INFO - Started process (PID=1278) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:14:27.600+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:14:27.602+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:14:27.602+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:14:27.616+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:14:27.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:14:27.620+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:14:27.635+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.040 seconds
[2024-10-06T20:14:57.873+0000] {processor.py:186} INFO - Started process (PID=1294) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:14:57.874+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:14:57.876+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:14:57.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:14:57.890+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:14:57.885+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:14:57.894+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:14:57.910+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.041 seconds
[2024-10-06T20:15:27.152+0000] {processor.py:186} INFO - Started process (PID=1310) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:15:27.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:15:27.154+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:15:27.154+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:15:27.178+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:15:27.172+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:15:27.182+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:15:27.200+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.053 seconds
[2024-10-06T20:15:53.378+0000] {processor.py:186} INFO - Started process (PID=1321) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:15:53.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:15:53.382+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:15:53.382+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:15:53.408+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:15:53.401+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:15:53.413+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:15:53.433+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.060 seconds
[2024-10-06T20:16:23.617+0000] {processor.py:186} INFO - Started process (PID=1337) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:16:23.618+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:16:23.620+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:16:23.619+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:16:23.634+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:16:23.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:16:23.639+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:16:23.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.043 seconds
[2024-10-06T20:16:53.903+0000] {processor.py:186} INFO - Started process (PID=1353) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:16:53.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:16:53.906+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:16:53.906+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:16:53.921+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:16:53.916+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:16:53.925+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:16:53.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.044 seconds
[2024-10-06T20:16:57.016+0000] {processor.py:186} INFO - Started process (PID=1363) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:16:57.017+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:16:57.020+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:16:57.019+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:16:57.044+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:16:57.038+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:16:57.048+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:16:57.064+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.052 seconds
[2024-10-06T20:17:14.159+0000] {processor.py:186} INFO - Started process (PID=1368) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:17:14.160+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:17:14.162+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:17:14.162+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:17:14.185+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:17:14.179+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:17:14.189+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:17:14.206+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.051 seconds
[2024-10-06T20:17:44.452+0000] {processor.py:186} INFO - Started process (PID=1384) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:17:44.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:17:44.455+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:17:44.454+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:17:44.471+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:17:44.465+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:17:44.475+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:17:44.491+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.044 seconds
[2024-10-06T20:17:46.496+0000] {processor.py:186} INFO - Started process (PID=1395) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:17:46.497+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:17:46.499+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:17:46.499+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:17:46.521+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:17:46.516+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:17:46.525+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:17:46.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.050 seconds
[2024-10-06T20:18:16.776+0000] {processor.py:186} INFO - Started process (PID=1411) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:18:16.777+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:18:16.779+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:18:16.778+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:18:16.794+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:18:16.788+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:18:16.798+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:18:16.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.043 seconds
[2024-10-06T20:18:47.044+0000] {processor.py:186} INFO - Started process (PID=1427) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:18:47.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:18:47.047+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:18:47.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:18:47.066+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:18:47.060+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:18:47.071+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:18:47.091+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.051 seconds
[2024-10-06T20:19:12.302+0000] {processor.py:186} INFO - Started process (PID=1437) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:19:12.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:19:12.305+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:19:12.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:19:12.331+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:19:12.323+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:19:12.336+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:19:12.358+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.061 seconds
[2024-10-06T20:19:42.592+0000] {processor.py:186} INFO - Started process (PID=1453) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:19:42.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:19:42.595+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:19:42.595+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:19:42.611+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:19:42.605+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:19:42.615+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:19:42.633+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.045 seconds
[2024-10-06T20:20:12.873+0000] {processor.py:186} INFO - Started process (PID=1469) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:20:12.874+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:20:12.876+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:20:12.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:20:12.891+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:20:12.886+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:20:12.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:20:12.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.044 seconds
[2024-10-06T20:20:43.175+0000] {processor.py:186} INFO - Started process (PID=1490) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:20:43.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:20:43.179+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:20:43.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:20:43.194+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:20:43.188+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:20:43.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:20:43.216+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.045 seconds
[2024-10-06T20:21:13.451+0000] {processor.py:186} INFO - Started process (PID=1506) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:21:13.452+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:21:13.455+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:21:13.454+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:21:13.471+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:21:13.464+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:21:13.476+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:21:13.495+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.050 seconds
[2024-10-06T20:21:45.837+0000] {processor.py:186} INFO - Started process (PID=1522) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:21:45.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-06T20:21:45.869+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:21:45.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:21:46.031+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:21:45.968+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-06T20:21:46.057+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-06T20:21:46.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.639 seconds
