[2024-10-06T19:13:51.957+0000] {processor.py:186} INFO - Started process (PID=3055) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:13:51.958+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:13:51.960+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:13:51.960+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:13:51.975+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:13:51.987+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.036 seconds
[2024-10-06T19:14:22.283+0000] {processor.py:186} INFO - Started process (PID=3346) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:14:22.284+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:14:22.286+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:14:22.286+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:14:22.296+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:14:22.306+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.027 seconds
[2024-10-06T19:14:52.685+0000] {processor.py:186} INFO - Started process (PID=3637) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:14:52.686+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:14:52.688+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:14:52.688+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:14:52.698+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:14:52.711+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.029 seconds
[2024-10-06T19:15:22.933+0000] {processor.py:186} INFO - Started process (PID=3928) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:15:22.934+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:15:22.935+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:15:22.935+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:15:22.945+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:15:22.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.027 seconds
[2024-10-06T19:15:27.995+0000] {processor.py:186} INFO - Started process (PID=3933) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:15:27.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:15:27.997+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:15:27.997+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:15:28.009+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:15:28.008+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 11
    
    ^
IndentationError: expected an indented block after 'with' statement on line 5
[2024-10-06T19:15:28.010+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:15:28.030+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-06T19:15:58.232+0000] {processor.py:186} INFO - Started process (PID=4224) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:15:58.232+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:15:58.234+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:15:58.234+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:15:58.249+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:15:58.249+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 11
    
    ^
IndentationError: expected an indented block after 'with' statement on line 5
[2024-10-06T19:15:58.250+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:15:58.265+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2024-10-06T19:16:28.469+0000] {processor.py:186} INFO - Started process (PID=4515) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:16:28.470+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:16:28.471+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:16:28.471+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:16:28.483+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:16:28.483+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 11
    
    ^
IndentationError: expected an indented block after 'with' statement on line 5
[2024-10-06T19:16:28.484+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:16:28.499+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.034 seconds
[2024-10-06T19:16:58.826+0000] {processor.py:186} INFO - Started process (PID=4806) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:16:58.827+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:16:58.829+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:16:58.829+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:16:58.840+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:16:58.839+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 11
    
    ^
IndentationError: expected an indented block after 'with' statement on line 5
[2024-10-06T19:16:58.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:16:58.856+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.034 seconds
[2024-10-06T19:17:29.193+0000] {processor.py:186} INFO - Started process (PID=5097) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:17:29.194+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:17:29.196+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:17:29.196+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:17:29.210+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:17:29.209+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 11
    
    ^
IndentationError: expected an indented block after 'with' statement on line 5
[2024-10-06T19:17:29.211+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:17:29.226+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-06T19:17:59.481+0000] {processor.py:186} INFO - Started process (PID=5388) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:17:59.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:17:59.484+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:17:59.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:17:59.497+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:17:59.496+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 11
    
    ^
IndentationError: expected an indented block after 'with' statement on line 5
[2024-10-06T19:17:59.497+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:17:59.513+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2024-10-06T19:18:24.734+0000] {processor.py:186} INFO - Started process (PID=5679) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:18:24.735+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:18:24.737+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:18:24.736+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:18:24.756+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:18:24.753+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2024-10-06T19:18:24.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:18:24.774+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.044 seconds
[2024-10-06T19:18:55.063+0000] {processor.py:186} INFO - Started process (PID=5970) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:18:55.063+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:18:55.065+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:18:55.065+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:18:55.080+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:18:55.077+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2024-10-06T19:18:55.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:18:55.104+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.046 seconds
[2024-10-06T19:18:57.097+0000] {processor.py:186} INFO - Started process (PID=5975) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:18:57.098+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:18:57.101+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:18:57.100+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:18:57.122+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:18:57.118+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2024-10-06T19:18:57.124+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:18:57.140+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.047 seconds
[2024-10-06T19:19:27.420+0000] {processor.py:186} INFO - Started process (PID=6266) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:19:27.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:19:27.423+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:19:27.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:19:27.437+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:19:27.434+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2024-10-06T19:19:27.439+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:19:27.456+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-06T19:19:52.654+0000] {processor.py:186} INFO - Started process (PID=6557) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:19:52.655+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:19:52.657+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:19:52.656+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:19:52.679+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:19:52.676+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:19:52.681+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:19:52.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.047 seconds
[2024-10-06T19:20:23.018+0000] {processor.py:186} INFO - Started process (PID=6848) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:20:23.019+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:20:23.020+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:20:23.020+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:20:23.033+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:20:23.030+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:20:23.034+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:20:23.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.036 seconds
[2024-10-06T19:20:53.540+0000] {processor.py:186} INFO - Started process (PID=7139) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:20:53.541+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:20:53.543+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:20:53.543+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:20:53.556+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:20:53.553+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:20:53.558+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:20:53.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.038 seconds
[2024-10-06T19:21:23.962+0000] {processor.py:186} INFO - Started process (PID=7430) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:21:23.963+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:21:23.966+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:21:23.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:21:23.980+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:21:23.976+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:21:23.982+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:21:24.006+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.048 seconds
[2024-10-06T19:21:31.035+0000] {processor.py:186} INFO - Started process (PID=7435) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:21:31.035+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:21:31.039+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:21:31.038+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:21:31.062+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:21:31.058+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:21:31.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:21:31.080+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.050 seconds
[2024-10-06T19:22:01.394+0000] {processor.py:186} INFO - Started process (PID=7726) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:22:01.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:22:01.397+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:22:01.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:22:01.409+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:22:01.406+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:22:01.411+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:22:01.429+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-10-06T19:27:54.586+0000] {processor.py:186} INFO - Started process (PID=170) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:27:54.588+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:27:54.591+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:27:54.591+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:27:54.609+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:27:54.603+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:27:54.611+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:27:54.639+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.063 seconds
[2024-10-06T19:28:20.781+0000] {processor.py:186} INFO - Started process (PID=182) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:28:20.781+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:28:20.784+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:28:20.784+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:28:20.805+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:28:20.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:28:20.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:28:20.826+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.050 seconds
[2024-10-06T19:28:50.991+0000] {processor.py:186} INFO - Started process (PID=193) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:28:50.992+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:28:50.994+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:28:50.994+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:28:51.007+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:28:51.004+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:28:51.009+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:28:51.026+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-06T19:29:21.204+0000] {processor.py:186} INFO - Started process (PID=204) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:29:21.205+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:29:21.209+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:29:21.208+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:29:21.222+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:29:21.218+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:29:21.223+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:29:21.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-06T19:29:51.411+0000] {processor.py:186} INFO - Started process (PID=215) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:29:51.412+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:29:51.415+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:29:51.414+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:29:51.431+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:29:51.425+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:29:51.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:29:51.450+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.044 seconds
[2024-10-06T19:30:21.633+0000] {processor.py:186} INFO - Started process (PID=226) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:30:21.634+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:30:21.636+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:30:21.636+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:30:21.649+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:30:21.646+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:30:21.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:30:21.670+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-10-06T19:30:51.832+0000] {processor.py:186} INFO - Started process (PID=237) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:30:51.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:30:51.834+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:30:51.834+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:30:51.846+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:30:51.844+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:30:51.847+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:30:51.862+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.034 seconds
[2024-10-06T19:31:22.102+0000] {processor.py:186} INFO - Started process (PID=248) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:31:22.103+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:31:22.106+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:31:22.106+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:31:22.125+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:31:22.120+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:31:22.127+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:31:22.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.054 seconds
[2024-10-06T19:31:52.298+0000] {processor.py:186} INFO - Started process (PID=259) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:31:52.299+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:31:52.301+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:31:52.301+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:31:52.315+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:31:52.311+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:31:52.316+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:31:52.333+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-06T19:32:22.542+0000] {processor.py:186} INFO - Started process (PID=270) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:32:22.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:32:22.545+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:32:22.544+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:32:22.559+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:32:22.555+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:32:22.560+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:32:22.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-06T19:32:52.746+0000] {processor.py:186} INFO - Started process (PID=281) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:32:52.747+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:32:52.749+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:32:52.748+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:32:52.762+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:32:52.759+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:32:52.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:32:52.780+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-06T19:33:22.993+0000] {processor.py:186} INFO - Started process (PID=292) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:33:22.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:33:22.996+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:33:22.996+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:33:23.010+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:33:23.007+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:33:23.012+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:33:23.030+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-10-06T19:33:53.198+0000] {processor.py:186} INFO - Started process (PID=303) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:33:53.199+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:33:53.202+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:33:53.201+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:33:53.215+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:33:53.211+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:33:53.216+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:33:53.236+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2024-10-06T19:34:07.327+0000] {processor.py:186} INFO - Started process (PID=308) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:34:07.328+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:34:07.330+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:34:07.330+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:34:07.352+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:34:07.348+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:34:07.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:34:07.369+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.046 seconds
[2024-10-06T19:34:22.453+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:34:22.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:34:22.456+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:34:22.456+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:34:22.478+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:34:22.473+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:34:22.479+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:34:22.496+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.048 seconds
[2024-10-06T19:34:52.664+0000] {processor.py:186} INFO - Started process (PID=330) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:34:52.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:34:52.666+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:34:52.666+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:34:52.678+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:34:52.675+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:34:52.680+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:34:52.696+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2024-10-06T19:35:22.885+0000] {processor.py:186} INFO - Started process (PID=341) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:35:22.886+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:35:22.888+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:35:22.887+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:35:22.902+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:35:22.899+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:35:22.903+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:35:22.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-06T19:35:53.093+0000] {processor.py:186} INFO - Started process (PID=352) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:35:53.094+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:35:53.095+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:35:53.095+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:35:53.110+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:35:53.107+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:35:53.111+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:35:53.128+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-06T19:36:04.183+0000] {processor.py:186} INFO - Started process (PID=357) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:36:04.184+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:36:04.187+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:36:04.187+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:36:04.220+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:36:04.216+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:36:04.222+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:36:04.238+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.059 seconds
[2024-10-06T19:36:12.284+0000] {processor.py:186} INFO - Started process (PID=368) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:36:12.285+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:36:12.288+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:36:12.287+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:36:12.308+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:36:12.304+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:36:12.310+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:36:12.327+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.048 seconds
[2024-10-06T19:36:21.375+0000] {processor.py:186} INFO - Started process (PID=373) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:36:21.376+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:36:21.378+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:36:21.378+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:36:21.398+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:36:21.395+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:36:21.400+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:36:21.417+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.047 seconds
[2024-10-06T19:36:51.609+0000] {processor.py:186} INFO - Started process (PID=384) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:36:51.609+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:36:51.612+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:36:51.611+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:36:51.626+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:36:51.622+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:36:51.627+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:36:51.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-06T19:37:21.810+0000] {processor.py:186} INFO - Started process (PID=395) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:37:21.811+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:37:21.814+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:37:21.813+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:37:21.827+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:37:21.824+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:37:21.828+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:37:21.845+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-06T19:37:52.048+0000] {processor.py:186} INFO - Started process (PID=406) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:37:52.049+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:37:52.051+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:37:52.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:37:52.064+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:37:52.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:37:52.065+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:37:52.081+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2024-10-06T19:38:22.287+0000] {processor.py:186} INFO - Started process (PID=417) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:38:22.288+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:38:22.290+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:38:22.290+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:38:22.308+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:38:22.304+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:38:22.310+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:38:22.328+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.046 seconds
[2024-10-06T19:38:52.486+0000] {processor.py:186} INFO - Started process (PID=428) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:38:52.487+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:38:52.489+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:38:52.489+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:38:52.502+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:38:52.499+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:38:52.503+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:38:52.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.038 seconds
[2024-10-06T19:39:22.711+0000] {processor.py:186} INFO - Started process (PID=439) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:39:22.712+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:39:22.714+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:39:22.714+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:39:22.728+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:39:22.725+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:39:22.729+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:39:22.746+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-06T19:39:52.910+0000] {processor.py:186} INFO - Started process (PID=450) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:39:52.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:39:52.913+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:39:52.913+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:39:52.926+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:39:52.922+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:39:52.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:39:52.946+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-10-06T19:40:23.130+0000] {processor.py:186} INFO - Started process (PID=461) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:40:23.131+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:40:23.133+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:40:23.133+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:40:23.146+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:40:23.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:40:23.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:40:23.165+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-06T19:40:53.331+0000] {processor.py:186} INFO - Started process (PID=472) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:40:53.332+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:40:53.334+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:40:53.334+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:40:53.347+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:40:53.344+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:40:53.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:40:53.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.038 seconds
[2024-10-06T19:41:23.548+0000] {processor.py:186} INFO - Started process (PID=483) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:41:23.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:41:23.551+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:41:23.551+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:41:23.564+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:41:23.560+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:41:23.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:41:23.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-06T19:41:33.627+0000] {processor.py:186} INFO - Started process (PID=488) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:41:33.628+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:41:33.630+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:41:33.630+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:41:33.650+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:41:33.646+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:41:33.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:41:33.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2024-10-06T19:41:42.733+0000] {processor.py:186} INFO - Started process (PID=499) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:41:42.734+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:41:42.736+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:41:42.735+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:41:42.759+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:41:42.755+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:41:42.760+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:41:42.776+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.048 seconds
[2024-10-06T19:42:12.942+0000] {processor.py:186} INFO - Started process (PID=510) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:42:12.943+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:42:12.945+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:42:12.945+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:42:12.961+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:42:12.957+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:42:12.962+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:42:12.980+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.044 seconds
[2024-10-06T19:42:43.179+0000] {processor.py:186} INFO - Started process (PID=521) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:42:43.180+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:42:43.184+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:42:43.183+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:42:43.200+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:42:43.196+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:42:43.202+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:42:43.224+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.050 seconds
[2024-10-06T19:43:13.412+0000] {processor.py:186} INFO - Started process (PID=532) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:43:13.413+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:43:13.415+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:43:13.414+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:43:13.429+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:43:13.425+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:43:13.430+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:43:13.445+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2024-10-06T19:43:43.631+0000] {processor.py:186} INFO - Started process (PID=543) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:43:43.632+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:43:43.634+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:43:43.634+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:43:43.649+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:43:43.646+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:43:43.652+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:43:43.672+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.045 seconds
[2024-10-06T19:44:10.834+0000] {processor.py:186} INFO - Started process (PID=548) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:44:10.835+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:44:10.838+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:44:10.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:44:10.860+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:44:10.857+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:44:10.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:44:10.879+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.050 seconds
[2024-10-06T19:44:41.048+0000] {processor.py:186} INFO - Started process (PID=559) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:44:41.049+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:44:41.052+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:44:41.052+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:44:41.068+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:44:41.064+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:44:41.069+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:44:41.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.046 seconds
[2024-10-06T19:45:11.274+0000] {processor.py:186} INFO - Started process (PID=570) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:45:11.275+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:45:11.277+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:45:11.276+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:45:11.290+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:45:11.286+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:45:11.291+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:45:11.306+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2024-10-06T19:45:41.491+0000] {processor.py:186} INFO - Started process (PID=581) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:45:41.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:45:41.495+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:45:41.495+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:45:41.512+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:45:41.507+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:45:41.513+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:45:41.532+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.046 seconds
[2024-10-06T19:46:11.706+0000] {processor.py:186} INFO - Started process (PID=592) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:46:11.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:46:11.710+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:46:11.709+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:46:11.724+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:46:11.720+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:46:11.726+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:46:11.744+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-10-06T19:46:41.924+0000] {processor.py:186} INFO - Started process (PID=603) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:46:41.925+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:46:41.927+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:46:41.927+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:46:41.940+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:46:41.936+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:46:41.941+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:46:41.958+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-06T19:47:05.090+0000] {processor.py:186} INFO - Started process (PID=614) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:47:05.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:47:05.094+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:47:05.094+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:47:05.118+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:47:05.114+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:47:05.120+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:47:05.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.052 seconds
[2024-10-06T19:47:35.315+0000] {processor.py:186} INFO - Started process (PID=625) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:47:35.315+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:47:35.318+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:47:35.318+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:47:35.332+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:47:35.328+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:47:35.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:47:35.351+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-10-06T19:48:05.551+0000] {processor.py:186} INFO - Started process (PID=636) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:48:05.552+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:48:05.554+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:48:05.554+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:48:05.568+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:48:05.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:48:05.569+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:48:05.587+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-10-06T19:48:35.753+0000] {processor.py:186} INFO - Started process (PID=647) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:48:35.754+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:48:35.756+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:48:35.756+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:48:35.768+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:48:35.765+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:48:35.769+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:48:35.787+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.038 seconds
[2024-10-06T19:49:05.961+0000] {processor.py:186} INFO - Started process (PID=658) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:49:05.962+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:49:05.965+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:49:05.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:49:05.979+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:49:05.976+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:49:05.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:49:06.002+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.046 seconds
[2024-10-06T19:49:36.174+0000] {processor.py:186} INFO - Started process (PID=669) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:49:36.174+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:49:36.177+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:49:36.177+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:49:36.190+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:49:36.186+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:49:36.191+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:49:36.210+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-10-06T19:50:06.392+0000] {processor.py:186} INFO - Started process (PID=680) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:50:06.393+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:50:06.396+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:50:06.395+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:50:06.410+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:50:06.407+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:50:06.412+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:50:06.429+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-10-06T19:50:36.598+0000] {processor.py:186} INFO - Started process (PID=691) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:50:36.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:50:36.601+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:50:36.601+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:50:36.613+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:50:36.610+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:50:36.614+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:50:36.633+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-06T19:51:06.811+0000] {processor.py:186} INFO - Started process (PID=703) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:51:06.812+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:51:06.815+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:51:06.815+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:51:06.829+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:51:06.826+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:51:06.831+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:51:06.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.044 seconds
[2024-10-06T19:51:37.020+0000] {processor.py:186} INFO - Started process (PID=714) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:51:37.021+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:51:37.024+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:51:37.024+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:51:37.037+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:51:37.034+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:51:37.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:51:37.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-06T19:52:07.237+0000] {processor.py:186} INFO - Started process (PID=725) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:52:07.238+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:52:07.239+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:52:07.239+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:52:07.253+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:52:07.250+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:52:07.254+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:52:07.270+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.038 seconds
[2024-10-06T19:52:10.272+0000] {processor.py:186} INFO - Started process (PID=730) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:52:10.273+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:52:10.275+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:52:10.274+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:52:10.294+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:52:10.291+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:52:10.296+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:52:10.312+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.045 seconds
[2024-10-06T19:52:40.504+0000] {processor.py:186} INFO - Started process (PID=741) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:52:40.505+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:52:40.507+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:52:40.507+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:52:40.519+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:52:40.516+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:52:40.520+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:52:40.536+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.035 seconds
[2024-10-06T19:53:10.732+0000] {processor.py:186} INFO - Started process (PID=752) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:53:10.733+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:53:10.735+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:53:10.734+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:53:10.747+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:53:10.744+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:53:10.748+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:53:10.764+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.036 seconds
[2024-10-06T19:53:24.834+0000] {processor.py:186} INFO - Started process (PID=763) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:53:24.835+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:53:24.838+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:53:24.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:53:24.858+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:53:24.856+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:53:24.860+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:53:24.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.048 seconds
[2024-10-06T19:53:55.065+0000] {processor.py:186} INFO - Started process (PID=775) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:53:55.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:53:55.068+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:53:55.068+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:53:55.082+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:53:55.077+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:53:55.083+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:53:55.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-06T19:54:25.268+0000] {processor.py:186} INFO - Started process (PID=786) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:54:25.269+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:54:25.272+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:54:25.271+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:54:25.285+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:54:25.282+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay':timedelta(minute=2),
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-10-06T19:54:25.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:54:25.305+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-10-06T19:54:44.417+0000] {processor.py:186} INFO - Started process (PID=797) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:54:44.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:54:44.420+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:54:44.420+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:54:44.441+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:54:44.437+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 14, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T19:54:44.443+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:54:44.460+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.046 seconds
[2024-10-06T19:55:14.617+0000] {processor.py:186} INFO - Started process (PID=808) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:55:14.618+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:55:14.619+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:55:14.619+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:55:14.631+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:55:14.628+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 14, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T19:55:14.632+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:55:14.650+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2024-10-06T19:55:44.834+0000] {processor.py:186} INFO - Started process (PID=819) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:55:44.835+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:55:44.838+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:55:44.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:55:44.851+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:55:44.847+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 14, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T19:55:44.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:55:44.870+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-10-06T19:56:15.030+0000] {processor.py:186} INFO - Started process (PID=830) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:56:15.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:56:15.033+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:56:15.033+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:56:15.047+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:56:15.043+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 14, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T19:56:15.048+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:56:15.064+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.038 seconds
[2024-10-06T19:56:45.242+0000] {processor.py:186} INFO - Started process (PID=841) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:56:45.243+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:56:45.245+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:56:45.244+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:56:45.258+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:56:45.254+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 14, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T19:56:45.259+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:56:45.274+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2024-10-06T19:57:14.446+0000] {processor.py:186} INFO - Started process (PID=852) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:57:14.447+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:57:14.449+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:57:14.449+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:57:14.472+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:57:14.467+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 14, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T19:57:14.474+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:57:14.489+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.047 seconds
[2024-10-06T19:57:44.649+0000] {processor.py:186} INFO - Started process (PID=863) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:57:44.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:57:44.652+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:57:44.652+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:57:44.671+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:57:44.667+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 14, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T19:57:44.673+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:57:44.688+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.044 seconds
[2024-10-06T19:58:07.871+0000] {processor.py:186} INFO - Started process (PID=868) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:58:07.872+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:58:07.875+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:58:07.874+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:58:07.895+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:58:07.891+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 14, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T19:58:07.896+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:58:07.916+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.052 seconds
[2024-10-06T19:58:16.958+0000] {processor.py:186} INFO - Started process (PID=879) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:58:16.959+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:58:16.961+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:58:16.960+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:58:16.981+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:58:16.978+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 14, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T19:58:16.983+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:58:17.004+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.053 seconds
[2024-10-06T19:58:40.156+0000] {processor.py:186} INFO - Started process (PID=884) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:58:40.157+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:58:40.159+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:58:40.159+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:58:40.180+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:58:40.177+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 14, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T19:58:40.182+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:58:40.201+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.050 seconds
[2024-10-06T19:59:10.366+0000] {processor.py:186} INFO - Started process (PID=895) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:59:10.367+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:59:10.369+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:59:10.368+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:59:10.383+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:59:10.380+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 14, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T19:59:10.384+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:59:10.401+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-06T19:59:29.540+0000] {processor.py:186} INFO - Started process (PID=906) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:59:29.540+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:59:29.543+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:59:29.542+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:59:29.565+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:59:29.562+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T19:59:29.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:59:29.588+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.053 seconds
[2024-10-06T19:59:59.748+0000] {processor.py:186} INFO - Started process (PID=917) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:59:59.749+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T19:59:59.751+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:59:59.751+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:59:59.765+0000] {logging_mixin.py:190} INFO - [2024-10-06T19:59:59.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T19:59:59.766+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T19:59:59.786+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2024-10-06T20:00:29.975+0000] {processor.py:186} INFO - Started process (PID=928) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:00:29.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:00:29.978+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:00:29.978+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:00:29.992+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:00:29.988+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:00:29.993+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:00:30.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-10-06T20:00:40.069+0000] {processor.py:186} INFO - Started process (PID=933) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:00:40.069+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:00:40.072+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:00:40.071+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:00:40.095+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:00:40.091+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:00:40.096+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:00:40.116+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.052 seconds
[2024-10-06T20:01:05.271+0000] {processor.py:186} INFO - Started process (PID=944) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:01:05.273+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:01:05.275+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:01:05.274+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:01:05.299+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:01:05.295+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:01:05.301+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:01:05.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.055 seconds
[2024-10-06T20:01:35.481+0000] {processor.py:186} INFO - Started process (PID=955) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:01:35.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:01:35.484+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:01:35.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:01:35.496+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:01:35.494+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:01:35.497+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:01:35.514+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2024-10-06T20:02:05.695+0000] {processor.py:186} INFO - Started process (PID=966) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:02:05.696+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:02:05.697+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:02:05.697+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:02:05.710+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:02:05.707+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:02:05.712+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:02:05.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2024-10-06T20:02:35.895+0000] {processor.py:186} INFO - Started process (PID=977) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:02:35.896+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:02:35.898+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:02:35.898+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:02:35.912+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:02:35.909+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:02:35.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:02:35.931+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-06T20:03:06.127+0000] {processor.py:186} INFO - Started process (PID=988) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:03:06.128+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:03:06.130+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:03:06.130+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:03:06.141+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:03:06.138+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:03:06.142+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:03:06.157+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.034 seconds
[2024-10-06T20:03:36.326+0000] {processor.py:186} INFO - Started process (PID=999) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:03:36.327+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:03:36.330+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:03:36.329+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:03:36.345+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:03:36.342+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:03:36.346+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:03:36.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-06T20:04:06.534+0000] {processor.py:186} INFO - Started process (PID=1010) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:04:06.535+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:04:06.537+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:04:06.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:04:06.551+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:04:06.547+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:04:06.552+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:04:06.568+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.038 seconds
[2024-10-06T20:04:36.738+0000] {processor.py:186} INFO - Started process (PID=1021) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:04:36.739+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:04:36.741+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:04:36.740+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:04:36.753+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:04:36.750+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:04:36.754+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:04:36.772+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-06T20:04:56.896+0000] {processor.py:186} INFO - Started process (PID=1032) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:04:56.897+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:04:56.899+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:04:56.899+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:04:56.922+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:04:56.918+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 23, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:04:56.924+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:04:56.940+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.049 seconds
[2024-10-06T20:05:27.126+0000] {processor.py:186} INFO - Started process (PID=1043) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:05:27.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:05:27.129+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:05:27.129+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:05:27.148+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:05:27.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 23, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:05:27.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:05:27.170+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.049 seconds
[2024-10-06T20:05:38.278+0000] {processor.py:186} INFO - Started process (PID=1048) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:05:38.279+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:05:38.281+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:05:38.281+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:05:38.302+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:05:38.299+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 23, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:05:38.304+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:05:38.322+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.047 seconds
[2024-10-06T20:06:08.471+0000] {processor.py:186} INFO - Started process (PID=1059) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:06:08.472+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:06:08.474+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:06:08.474+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:06:08.488+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:06:08.484+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 23, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:06:08.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:06:08.509+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-10-06T20:06:38.696+0000] {processor.py:186} INFO - Started process (PID=1070) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:06:38.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:06:38.699+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:06:38.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:06:38.712+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:06:38.709+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 23, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:06:38.714+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:06:38.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-06T20:06:40.739+0000] {processor.py:186} INFO - Started process (PID=1075) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:06:40.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:06:40.743+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:06:40.742+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:06:40.764+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:06:40.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 24, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:06:40.765+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:06:40.782+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.048 seconds
[2024-10-06T20:07:10.967+0000] {processor.py:186} INFO - Started process (PID=1086) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:07:10.969+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:07:10.972+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:07:10.971+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:07:10.986+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:07:10.983+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 24, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:07:10.988+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:07:11.010+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.051 seconds
[2024-10-06T20:07:14.017+0000] {processor.py:186} INFO - Started process (PID=1097) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:07:14.018+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:07:14.020+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:07:14.019+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:07:14.038+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:07:14.034+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 25, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:07:14.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:07:14.058+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.045 seconds
[2024-10-06T20:07:44.303+0000] {processor.py:186} INFO - Started process (PID=1108) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:07:44.305+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:07:44.308+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:07:44.308+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:07:44.325+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:07:44.322+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 25, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:07:44.327+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:07:44.348+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.056 seconds
[2024-10-06T20:08:14.550+0000] {processor.py:186} INFO - Started process (PID=1119) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:08:14.552+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:08:14.555+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:08:14.554+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:08:14.571+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:08:14.567+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 25, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:08:14.573+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:08:14.596+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.050 seconds
[2024-10-06T20:08:44.762+0000] {processor.py:186} INFO - Started process (PID=1130) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:08:44.764+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:08:44.767+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:08:44.766+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:08:44.782+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:08:44.778+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 25, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:08:44.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:08:44.806+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.049 seconds
[2024-10-06T20:09:14.974+0000] {processor.py:186} INFO - Started process (PID=1141) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:09:14.975+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:09:14.977+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:09:14.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:09:14.991+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:09:14.988+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 25, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:09:14.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:09:15.008+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-06T20:09:45.204+0000] {processor.py:186} INFO - Started process (PID=1152) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:09:45.205+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:09:45.208+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:09:45.207+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:09:45.220+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:09:45.217+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 25, in <module>
    start_date=datetime(2024,23,5),
               ^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12
[2024-10-06T20:09:45.222+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:09:45.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-06T20:09:57.311+0000] {processor.py:186} INFO - Started process (PID=1157) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:09:57.312+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:09:57.315+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:09:57.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:09:57.333+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:09:57.331+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:09:57.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:09:57.353+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.048 seconds
[2024-10-06T20:10:21.504+0000] {processor.py:186} INFO - Started process (PID=1168) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:10:21.505+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:10:21.509+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:10:21.508+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:10:21.530+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:10:21.528+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:10:21.531+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:10:21.552+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.053 seconds
[2024-10-06T20:10:51.719+0000] {processor.py:186} INFO - Started process (PID=1179) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:10:51.721+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:10:51.724+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:10:51.724+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:10:51.740+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:10:51.739+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:10:51.741+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:10:51.760+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.047 seconds
[2024-10-06T20:11:21.955+0000] {processor.py:186} INFO - Started process (PID=1191) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:11:21.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:11:21.958+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:11:21.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:11:21.973+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:11:21.972+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:11:21.974+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:11:21.994+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.044 seconds
[2024-10-06T20:11:52.155+0000] {processor.py:186} INFO - Started process (PID=1202) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:11:52.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:11:52.159+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:11:52.158+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:11:52.175+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:11:52.173+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:11:52.175+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:11:52.192+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-10-06T20:12:22.386+0000] {processor.py:186} INFO - Started process (PID=1214) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:12:22.387+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:12:22.389+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:12:22.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:12:22.403+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:12:22.402+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:12:22.404+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:12:22.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-10-06T20:12:52.588+0000] {processor.py:186} INFO - Started process (PID=1225) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:12:52.589+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:12:52.592+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:12:52.591+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:12:52.606+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:12:52.605+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:12:52.607+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:12:52.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-10-06T20:13:22.998+0000] {processor.py:186} INFO - Started process (PID=1241) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:13:22.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:13:23.001+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:13:23.000+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:13:23.017+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:13:23.016+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:13:23.018+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:13:23.037+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.044 seconds
[2024-10-06T20:13:53.279+0000] {processor.py:186} INFO - Started process (PID=1257) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:13:53.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:13:53.282+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:13:53.282+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:13:53.295+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:13:53.294+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:13:53.295+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:13:53.312+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2024-10-06T20:14:23.559+0000] {processor.py:186} INFO - Started process (PID=1273) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:14:23.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:14:23.562+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:14:23.562+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:14:23.576+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:14:23.575+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:14:23.577+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:14:23.593+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.038 seconds
[2024-10-06T20:14:53.827+0000] {processor.py:186} INFO - Started process (PID=1289) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:14:53.828+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:14:53.831+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:14:53.830+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:14:53.845+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:14:53.844+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:14:53.845+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:14:53.862+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-06T20:15:24.104+0000] {processor.py:186} INFO - Started process (PID=1305) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:15:24.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:15:24.107+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:15:24.107+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:15:24.120+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:15:24.119+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:15:24.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:15:24.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.038 seconds
[2024-10-06T20:15:54.402+0000] {processor.py:186} INFO - Started process (PID=1326) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:15:54.403+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:15:54.406+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:15:54.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:15:54.422+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:15:54.421+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:15:54.422+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:15:54.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-10-06T20:16:24.655+0000] {processor.py:186} INFO - Started process (PID=1342) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:16:24.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:16:24.657+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:16:24.657+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:16:24.669+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:16:24.668+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:16:24.669+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:16:24.685+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.034 seconds
[2024-10-06T20:16:54.928+0000] {processor.py:186} INFO - Started process (PID=1358) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:16:54.928+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:16:54.930+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:16:54.930+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:16:54.946+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:16:54.945+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:16:54.947+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:16:54.964+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-06T20:17:25.279+0000] {processor.py:186} INFO - Started process (PID=1379) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:17:25.279+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:17:25.281+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:17:25.281+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:17:25.295+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:17:25.294+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:17:25.296+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:17:25.313+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-06T20:17:55.603+0000] {processor.py:186} INFO - Started process (PID=1400) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:17:55.604+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:17:55.606+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:17:55.606+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:17:55.619+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:17:55.618+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:17:55.620+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:17:55.635+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2024-10-06T20:18:25.885+0000] {processor.py:186} INFO - Started process (PID=1416) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:18:25.886+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:18:25.888+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:18:25.888+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:18:25.902+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:18:25.901+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:18:25.902+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:18:25.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-06T20:18:56.141+0000] {processor.py:186} INFO - Started process (PID=1432) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:18:56.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:18:56.144+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:18:56.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:18:56.158+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:18:56.157+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:18:56.159+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:18:56.180+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.044 seconds
[2024-10-06T20:19:26.414+0000] {processor.py:186} INFO - Started process (PID=1448) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:19:26.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:19:26.417+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:19:26.417+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:19:26.431+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:19:26.429+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:19:26.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:19:26.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-06T20:19:56.712+0000] {processor.py:186} INFO - Started process (PID=1464) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:19:56.713+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:19:56.714+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:19:56.714+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:19:56.729+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:19:56.728+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:19:56.730+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:19:56.747+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-06T20:20:26.987+0000] {processor.py:186} INFO - Started process (PID=1480) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:20:26.988+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:20:26.989+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:20:26.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:20:27.004+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:20:27.003+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:20:27.005+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:20:27.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.038 seconds
[2024-10-06T20:20:28.048+0000] {processor.py:186} INFO - Started process (PID=1485) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:20:28.049+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:20:28.051+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:20:28.050+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:20:28.064+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:20:28.063+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:20:28.065+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:20:28.080+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.036 seconds
[2024-10-06T20:20:58.322+0000] {processor.py:186} INFO - Started process (PID=1501) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:20:58.323+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:20:58.326+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:20:58.326+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:20:58.343+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:20:58.342+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:20:58.344+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:20:58.360+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2024-10-06T20:21:28.607+0000] {processor.py:186} INFO - Started process (PID=1517) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:21:28.608+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-06T20:21:28.611+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:21:28.610+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:21:28.629+0000] {logging_mixin.py:190} INFO - [2024-10-06T20:21:28.628+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-06T20:21:28.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-06T20:21:28.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.046 seconds
