[2024-10-07T00:23:29.980+0000] {processor.py:186} INFO - Started process (PID=1536) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:23:29.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:23:29.989+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:23:29.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:23:30.033+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:23:30.024+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:23:30.047+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:23:30.103+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.135 seconds
[2024-10-07T00:24:00.344+0000] {processor.py:186} INFO - Started process (PID=1552) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:24:00.344+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:24:00.346+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:24:00.346+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:24:00.364+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:24:00.357+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:24:00.367+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:24:00.383+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.043 seconds
[2024-10-07T00:24:30.606+0000] {processor.py:186} INFO - Started process (PID=1568) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:24:30.606+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:24:30.608+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:24:30.607+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:24:30.618+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:24:30.614+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:24:30.622+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:24:30.634+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.032 seconds
[2024-10-07T00:33:12.924+0000] {processor.py:186} INFO - Started process (PID=1584) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:33:12.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:33:12.926+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:33:12.925+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:33:12.939+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:33:12.934+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:33:12.943+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:33:12.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.039 seconds
[2024-10-07T00:33:43.172+0000] {processor.py:186} INFO - Started process (PID=1600) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:33:43.173+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:33:43.176+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:33:43.175+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:33:43.194+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:33:43.186+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:33:43.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:33:43.217+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.050 seconds
[2024-10-07T00:34:13.475+0000] {processor.py:186} INFO - Started process (PID=1616) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:34:13.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:34:13.478+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:34:13.478+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:34:13.494+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:34:13.488+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:34:13.498+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:34:13.515+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.044 seconds
[2024-10-07T00:34:43.762+0000] {processor.py:186} INFO - Started process (PID=1632) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:34:43.763+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:34:43.765+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:34:43.765+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:34:43.783+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:34:43.776+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:34:43.787+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:34:43.806+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.050 seconds
[2024-10-07T00:35:14.054+0000] {processor.py:186} INFO - Started process (PID=1648) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:35:14.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:35:14.057+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:35:14.057+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:35:14.075+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:35:14.069+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:35:14.081+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:35:14.100+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.050 seconds
[2024-10-07T00:35:44.343+0000] {processor.py:186} INFO - Started process (PID=1664) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:35:44.344+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:35:44.345+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:35:44.345+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:35:44.364+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:35:44.357+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:35:44.370+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:35:44.389+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.051 seconds
[2024-10-07T00:36:14.665+0000] {processor.py:186} INFO - Started process (PID=1680) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:36:14.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:36:14.668+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:36:14.668+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:36:14.684+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:36:14.678+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:36:14.689+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:36:14.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.051 seconds
[2024-10-07T00:36:44.970+0000] {processor.py:186} INFO - Started process (PID=1696) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:36:44.971+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:36:44.973+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:36:44.973+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:36:44.991+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:36:44.985+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:36:44.995+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:36:45.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.046 seconds
[2024-10-07T00:37:15.292+0000] {processor.py:186} INFO - Started process (PID=1712) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:37:15.293+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:37:15.296+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:37:15.295+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:37:15.317+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:37:15.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:37:15.324+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:37:15.351+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.065 seconds
[2024-10-07T00:37:45.577+0000] {processor.py:186} INFO - Started process (PID=1728) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:37:45.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:37:45.580+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:37:45.580+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:37:45.596+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:37:45.590+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:37:45.601+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:37:45.619+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.048 seconds
[2024-10-07T00:38:15.862+0000] {processor.py:186} INFO - Started process (PID=1744) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:38:15.862+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:38:15.865+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:38:15.864+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:38:15.883+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:38:15.876+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:38:15.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:38:15.910+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.054 seconds
[2024-10-07T00:38:46.166+0000] {processor.py:186} INFO - Started process (PID=1760) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:38:46.167+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:38:46.169+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:38:46.168+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:38:46.186+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:38:46.179+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:38:46.190+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:38:46.209+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.048 seconds
[2024-10-07T00:39:16.472+0000] {processor.py:186} INFO - Started process (PID=1776) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:39:16.472+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:39:16.474+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:39:16.474+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:39:16.491+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:39:16.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:39:16.495+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:39:16.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.046 seconds
[2024-10-07T00:39:46.776+0000] {processor.py:186} INFO - Started process (PID=1792) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:39:46.777+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:39:46.779+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:39:46.779+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:39:46.797+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:39:46.791+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:39:46.802+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:39:46.820+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.054 seconds
[2024-10-07T00:40:17.082+0000] {processor.py:186} INFO - Started process (PID=1808) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:40:17.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:40:17.085+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:40:17.085+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:40:17.100+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:40:17.094+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:40:17.105+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:40:17.121+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.045 seconds
[2024-10-07T00:40:47.368+0000] {processor.py:186} INFO - Started process (PID=1824) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:40:47.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:40:47.371+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:40:47.371+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:40:47.387+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:40:47.381+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:40:47.392+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:40:47.409+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.047 seconds
[2024-10-07T00:41:17.677+0000] {processor.py:186} INFO - Started process (PID=1840) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:41:17.678+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:41:17.680+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:41:17.680+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:41:17.698+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:41:17.692+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:41:17.703+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:41:17.720+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.048 seconds
[2024-10-07T00:41:47.973+0000] {processor.py:186} INFO - Started process (PID=1856) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:41:47.973+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:41:47.975+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:41:47.975+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:41:47.992+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:41:47.986+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:41:47.996+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:41:48.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.045 seconds
[2024-10-07T00:42:18.268+0000] {processor.py:186} INFO - Started process (PID=1872) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:42:18.269+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:42:18.271+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:42:18.271+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:42:18.287+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:42:18.282+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:42:18.292+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:42:18.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.049 seconds
[2024-10-07T00:42:48.555+0000] {processor.py:186} INFO - Started process (PID=1888) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:42:48.555+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:42:48.558+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:42:48.557+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:42:48.574+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:42:48.568+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:42:48.579+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:42:48.596+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.046 seconds
[2024-10-07T00:43:18.892+0000] {processor.py:186} INFO - Started process (PID=1904) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:43:18.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:43:18.895+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:43:18.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:43:18.915+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:43:18.909+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:43:18.920+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:43:18.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.049 seconds
[2024-10-07T00:43:49.207+0000] {processor.py:186} INFO - Started process (PID=1920) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:43:49.207+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:43:49.210+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:43:49.209+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:43:49.226+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:43:49.219+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:43:49.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:43:49.246+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.043 seconds
[2024-10-07T00:44:19.498+0000] {processor.py:186} INFO - Started process (PID=1936) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:44:19.499+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:44:19.501+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:44:19.501+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:44:19.517+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:44:19.511+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:44:19.522+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:44:19.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.044 seconds
[2024-10-07T00:44:49.787+0000] {processor.py:186} INFO - Started process (PID=1952) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:44:49.788+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:44:49.790+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:44:49.790+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:44:49.808+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:44:49.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:44:49.812+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:44:49.827+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.046 seconds
[2024-10-07T00:45:20.020+0000] {processor.py:186} INFO - Started process (PID=1968) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:45:20.021+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:45:20.023+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:45:20.023+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:45:20.038+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:45:20.032+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:45:20.042+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:45:20.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.042 seconds
[2024-10-07T00:45:50.271+0000] {processor.py:186} INFO - Started process (PID=1984) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:45:50.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:45:50.273+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:45:50.273+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:45:50.290+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:45:50.283+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:45:50.295+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:45:50.313+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.047 seconds
[2024-10-07T00:46:20.562+0000] {processor.py:186} INFO - Started process (PID=2000) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:46:20.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:46:20.565+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:46:20.565+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:46:20.580+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:46:20.575+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:46:20.585+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:46:20.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.042 seconds
[2024-10-07T00:46:50.848+0000] {processor.py:186} INFO - Started process (PID=2016) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:46:50.849+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:46:50.851+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:46:50.850+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:46:50.868+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:46:50.861+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:46:50.872+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:46:50.888+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.043 seconds
[2024-10-07T00:47:21.146+0000] {processor.py:186} INFO - Started process (PID=2032) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:47:21.146+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:47:21.149+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:47:21.149+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:47:21.166+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:47:21.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:47:21.170+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:47:21.189+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.049 seconds
[2024-10-07T00:47:51.437+0000] {processor.py:186} INFO - Started process (PID=2048) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:47:51.438+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:47:51.440+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:47:51.440+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:47:51.457+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:47:51.451+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:47:51.462+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:47:51.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.048 seconds
[2024-10-07T00:48:21.766+0000] {processor.py:186} INFO - Started process (PID=2064) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:48:21.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:48:21.768+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:48:21.768+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:48:21.785+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:48:21.779+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:48:21.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:48:21.806+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.047 seconds
[2024-10-07T00:48:52.057+0000] {processor.py:186} INFO - Started process (PID=2080) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:48:52.057+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:48:52.059+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:48:52.059+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:48:52.073+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:48:52.068+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:48:52.078+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:48:52.095+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.043 seconds
[2024-10-07T00:49:22.347+0000] {processor.py:186} INFO - Started process (PID=2096) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:49:22.347+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:49:22.349+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:49:22.349+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:49:22.366+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:49:22.360+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:49:22.371+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:49:22.387+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.045 seconds
[2024-10-07T00:49:52.626+0000] {processor.py:186} INFO - Started process (PID=2112) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:49:52.626+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:49:52.628+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:49:52.628+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:49:52.642+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:49:52.637+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:49:52.646+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:49:52.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.039 seconds
[2024-10-07T00:50:22.908+0000] {processor.py:186} INFO - Started process (PID=2128) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:50:22.909+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:50:22.911+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:50:22.911+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:50:22.926+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:50:22.920+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:50:22.930+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:50:22.949+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.045 seconds
[2024-10-07T00:50:53.152+0000] {processor.py:186} INFO - Started process (PID=2144) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:50:53.152+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:50:53.155+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:50:53.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:50:53.172+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:50:53.166+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:50:53.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:50:53.193+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.047 seconds
[2024-10-07T00:51:23.449+0000] {processor.py:186} INFO - Started process (PID=2160) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:51:23.450+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:51:23.455+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:51:23.454+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:51:23.470+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:51:23.465+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:51:23.475+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:51:23.555+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.116 seconds
[2024-10-07T00:51:53.822+0000] {processor.py:186} INFO - Started process (PID=2176) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:51:53.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:51:53.825+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:51:53.825+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:51:53.841+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:51:53.836+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:51:53.845+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:51:53.868+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.054 seconds
[2024-10-07T00:52:24.130+0000] {processor.py:186} INFO - Started process (PID=2192) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:52:24.131+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:52:24.133+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:52:24.133+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:52:24.151+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:52:24.145+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:52:24.156+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:52:24.174+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.050 seconds
[2024-10-07T00:52:54.427+0000] {processor.py:186} INFO - Started process (PID=2208) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:52:54.427+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:52:54.430+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:52:54.429+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:52:54.444+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:52:54.439+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:52:54.448+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:52:54.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.044 seconds
[2024-10-07T00:53:24.737+0000] {processor.py:186} INFO - Started process (PID=2224) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:53:24.738+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:53:24.740+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:53:24.740+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:53:24.755+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:53:24.750+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:53:24.759+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:53:24.776+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.044 seconds
[2024-10-07T00:53:55.032+0000] {processor.py:186} INFO - Started process (PID=2240) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:53:55.033+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:53:55.037+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:53:55.036+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:53:55.053+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:53:55.048+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:53:55.058+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:53:55.076+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.049 seconds
[2024-10-07T00:54:25.317+0000] {processor.py:186} INFO - Started process (PID=2256) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:54:25.318+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:54:25.320+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:54:25.320+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:54:25.335+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:54:25.329+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:54:25.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:54:25.355+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.043 seconds
[2024-10-07T00:54:55.583+0000] {processor.py:186} INFO - Started process (PID=2272) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:54:55.584+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:54:55.586+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:54:55.586+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:54:55.602+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:54:55.596+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:54:55.606+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:54:55.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.045 seconds
[2024-10-07T00:55:25.869+0000] {processor.py:186} INFO - Started process (PID=2288) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:55:25.869+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:55:25.871+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:55:25.871+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:55:25.886+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:55:25.880+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:55:25.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:55:25.905+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.040 seconds
[2024-10-07T00:55:56.159+0000] {processor.py:186} INFO - Started process (PID=2304) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:55:56.159+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:55:56.161+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:55:56.161+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:55:56.176+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:55:56.170+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:55:56.180+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:55:56.196+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.042 seconds
[2024-10-07T00:56:26.435+0000] {processor.py:186} INFO - Started process (PID=2321) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:56:26.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:56:26.437+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:56:26.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:56:26.453+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:56:26.447+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:56:26.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:56:26.474+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.043 seconds
[2024-10-07T00:56:56.713+0000] {processor.py:186} INFO - Started process (PID=2337) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:56:56.713+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:56:56.716+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:56:56.716+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:56:56.732+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:56:56.726+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:56:56.737+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:56:56.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.043 seconds
[2024-10-07T00:57:26.987+0000] {processor.py:186} INFO - Started process (PID=2353) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:57:26.987+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:57:26.990+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:57:26.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:57:27.005+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:57:26.999+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:57:27.009+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:57:27.024+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.042 seconds
[2024-10-07T00:57:57.265+0000] {processor.py:186} INFO - Started process (PID=2369) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:57:57.266+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:57:57.268+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:57:57.268+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:57:57.283+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:57:57.278+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:57:57.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:57:57.307+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.047 seconds
[2024-10-07T00:58:27.598+0000] {processor.py:186} INFO - Started process (PID=2385) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:58:27.599+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:58:27.602+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:58:27.601+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:58:27.622+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:58:27.615+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:58:27.628+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:58:27.650+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.058 seconds
[2024-10-07T00:58:57.886+0000] {processor.py:186} INFO - Started process (PID=2401) to work on /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:58:57.887+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_with_taskflow.py for tasks to queue
[2024-10-07T00:58:57.889+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:58:57.889+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:58:57.905+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:58:57.900+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow.py", line 6, in <module>
    'retry_delay':timedelta(minutes=2),
                  ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-07T00:58:57.910+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow.py
[2024-10-07T00:58:57.926+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_with_taskflow.py took 0.044 seconds
